baseurl: "https://facebymarlenek.com.au/"

# override .Site.Title for copyright notice
# copyright: "Custom Business Name"

# disableKinds: ["taxonomy", "taxonomyTerm"]
#disableKinds: [taxonomyTerm]
enableEmoji: true
enableGitInfo: false # does this default to false? delete??
enableRobotsTXT: true

# googleAnalytics: 

# for xml output
languageCode: "en-au"
# for website
defaultContentLanguage: "en-au"

#pagination 
paginate: 6
rssLimit: 10

title: Face by Marlene K

#summary length (words)
summaryLength: 15

# add redirects/headers (netlify)
outputs:
  home: ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    suffixes: [""]
    delimiter: ""


outputFormats:
  # add output format for netlify _redirects  
  REDIRECTS:
    mediatype: "text/netlify"
    baseName: "_redirects"
    isPlainText: true
    notAlternative: true
  # add output format for netlify _headers
  HEADERS:
    mediatype: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

caches:
    getjson:
      dir: ":cacheDir/:project"
      maxAge: "10s"

# sitemap:
#   changefreq: "monthly"
#   filename: "sitemap.xml"
#   priority: 0.5

taxonomies:
  category: "categories"

# permalinks:
#   blog: "/:title/"
#   # categories: "/shop/:section/:title"
#   shop: "/shop/:slug"
#   #categories: "/shop/:section/:slug"
#   categories: "/shop/:slug"





# import modules
module:
  imports:
  - path: github.com/future-wd/hugo-image/v2
  - path: github.com/future-wd/hugo-svg-font/v2
  - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
  - path: github.com/future-wd/hugo-snipcart/v3
  - path: github.com/future-wd/hugo-contact-form-xhr/v2