## Page Title
titleSeparator: "-"
# only used on home page
# titleAddition: "hand made from pure ingredients found in nature."
titleAddition: All Natural Ingredients
# fall back description if a page does not have a description.
description: |-
  Marlene K has been running Face by Marlene K for over 20 years in Cecil Hills in South Western Sydney. With a whole range of beauty treatments starting from waxing spray tanning to specialised custom facials including Needling or BB glow. However her passion and speciality is in the area of cosmetic tattooing. With years of experience she has mastered the techniques of Micro blading, Ombre Eyebrows, Lip Blush and Scalp Pigmentation.

## Open Graph/JSON-LD

## Twitter Cards
# twitterSite: "@gethyas"
# twitterCreator: "@henkverlinde"

## JSON-LD
# schemaType: "Person"
# schemaType: "Organization"
# schemaName: "Hyas"
# schemaAuthor: "Henk Verlinde"
# schemaAuthorTwitter: "https://twitter.com/henkverlinde"
# schemaAuthorLinkedIn: "https://www.linkedin.com/in/henkverlinde/"
# schemaAuthorGitHub: "https://github.com/h-enk"
# schemaLocale: "en-US"
# schemaLogo: "logo-hyas.png"
# schemaLogoWidth: 512
# schemaLogoHeight: 512
# schemaImage: "hyas.png"
# schemaImageWidth: 1280
# schemaImageHeight: 640
# schemaTwitter: "https://twitter.com/gethyas"
# schemaLinkedIn: ""
# schemaGitHub: "https://github.com/h-enk/hyas"

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
landscapePhotoWidths: [900, 800, 700, 600, 500]
portraitPhotoWidths: [800, 700, 600, 500]
lqipWidth: "20x"
smallLimit: "300"

# Footer - override default copyright message
# footer: "Custom Footer Text"

# Alert
alert: false
alertText: Free shipping across Australia on orders over $100






snipcart:
  enabled: true # defaults to true
  key: NGUxMjlkZjUtNjAxNC00OGY3LWJjNWItOTRjMzkzZTk2NzU1NjM3Nzg4MDk4NTI5MjU1Njk5
  side: true # or false for full screen cart
  bootstrap: true # enables snipcart z-index css for bootstrap compatibility 

# netlify cms
headerScript:
  lang: JavaScript
  code: >-

footerScript:
  lang: JavaScript
  code: >-
    